main: fr.teddy.entityonlymcplugin.EntityOnly
name: EntityOnly
version: 0.1-SNAPSHOT
commands:
  setpos1:
    description: Set pos1 for area
    usage: /setpos1
  setpos2:
    description: Set pos2 for area
    usage: /setpos2
  apply:
    description: Transforms every blocks between pos1 and pos2 into entities
    usage: /apply